# Example values file for JWT Authentication with dynamic Keycloak detection
# This demonstrates how to enable JWT auth with auto-detected Keycloak

# Enable JWT authentication
jwt_auth:
  enabled: true  # Set to true to enable JWT authentication

  # Envoy proxy configuration (using Red Hat images)
  envoy:
    image:
      repository: registry.redhat.io/openshift-service-mesh/proxyv2-rhel9
      tag: "2.4-latest"

  # Keycloak configuration
  keycloak:
    issuer:
      # Leave baseUrl empty for auto-detection of Keycloak in the cluster
      # The chart will automatically find Keycloak routes/ingresses
      baseUrl: ""  # Auto-detect Keycloak URL
      realm: kubernetes  # Your Keycloak realm name

    # Valid audiences for JWT tokens
    audiences:
      - cost-management-operator
      - openshift-oidc

  # Authorino service configuration
  authorino:
    # Install Authorino operator (required)
    operator:
      install: true  # Automatically install the operator via OLM
      
    # Deploy Authorino in the same namespace (recommended)
    deploy:
      enabled: true
      name: ros-authorino

      # Use Red Hat Authorino image
      image:
        repository: registry.redhat.io/rhosak/authorino-rhel8
        tag: "1.0.0"

      logLevel: info

    # For using existing external Authorino instance
    # (uncomment and disable deploy.enabled if needed)
    # service:
    #   namespace: costmanagement-metrics-operator
    #   name: authorino-authorino-authorization
    #   port: 50051

    authConfig:
      name: ros-ingress-keycloak-auth
      create: true

# Alternative: Manual Keycloak URL specification
# Uncomment and modify if you want to specify the URL explicitly:
#
# jwt_auth:
#   enabled: true
#   keycloak:
#     issuer:
#       baseUrl: https://keycloak.mydomain.com  # Explicit URL
#       realm: kubernetes
#     audiences:
#       - cost-management-operator

# Alternative: Different Authorino instance
# Uncomment if you want to use Authorino in the ros-ocp namespace:
#
# jwt_auth:
#   enabled: true
#   authorino:
#     service:
#       namespace: ros-ocp  # Same namespace as ROS ingress
#       name: ros-authorino
#       port: 50051
