# Authorino Operator Installation
# Apply this file before deploying the ROS Helm chart with JWT authentication
# 
# Usage:
#   oc apply -f scripts/install-authorino-operator.yaml
#   
# Wait for operator to be ready (2-3 minutes), then:
#   helm install ros-ocp . --set jwt_auth.enabled=true

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: authorino-operator
  namespace: openshift-operators
  labels:
    app.kubernetes.io/name: authorino-operator
    app.kubernetes.io/part-of: ros-ocp-jwt-auth
spec:
  channel: stable
  name: authorino-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
  config:
    # Resource limits for the operator
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
