{{- if and .Values.jwt_auth.enabled .Values.jwt_auth.authorino.deploy.enabled .Values.jwt_auth.authorino.operator.install }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: authorino-operator
  namespace: {{ .Values.jwt_auth.authorino.operator.namespace | default "openshift-operators" }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: authorino-operator
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
spec:
  channel: {{ .Values.jwt_auth.authorino.operator.channel | default "stable" }}
  name: authorino-operator
  source: {{ .Values.jwt_auth.authorino.operator.source | default "redhat-operators" }}
  sourceNamespace: {{ .Values.jwt_auth.authorino.operator.sourceNamespace | default "openshift-marketplace" }}
  installPlanApproval: {{ .Values.jwt_auth.authorino.operator.installPlanApproval | default "Automatic" }}
{{- end }}
