{{- if eq (include "ros-ocp.jwt.shouldEnable" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ros-ocp.fullname" . }}-envoy-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    # Envoy configuration with Native JWT Authentication
    # This replaces the previous Authorino ext_authz approach to support multipart uploads
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: {{ .Values.jwt_auth.envoy.port }}
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ros_ingress_jwt_http
              codec_type: AUTO
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              route_config:
                name: local_route
                virtual_hosts:
                - name: ros_ingress_backend
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: ros-ingress-backend
              http_filters:
              # Native JWT Authentication filter - validates JWT inline without external service
              - name: envoy.filters.http.jwt_authn
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                  providers:
                    keycloak:
                      issuer: "{{ .Values.jwt_auth.keycloak.url }}/auth/realms/{{ .Values.jwt_auth.keycloak.realm }}"
                      audiences:
                      {{- range .Values.jwt_auth.keycloak.audiences }}
                      - {{ . | quote }}
                      {{- end }}
                      remote_jwks:
                        http_uri:
                          uri: "{{ .Values.jwt_auth.keycloak.url }}/auth/realms/{{ .Values.jwt_auth.keycloak.realm }}/protocol/openid-connect/certs"
                          cluster: keycloak_jwks
                          timeout: 5s
                        cache_duration:
                          seconds: 300
                      # Store JWT payload in metadata for Lua filter to extract
                      payload_in_metadata: "jwt_payload"
                      # Forward Authorization header to backend
                      forward: true
                  rules:
                  # Require JWT for API endpoints
                  - match:
                      prefix: "/api/ingress"
                    requires:
                      provider_name: "keycloak"
                  # Health endpoints don't require authentication
                  - match:
                      prefix: "/health"
                  - match:
                      prefix: "/ready"

              # Lua filter to extract JWT claims and inject X-ROS headers
              # This replicates what Authorino did but works with multipart requests
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                  inline_code: |
                    function envoy_on_request(request_handle)
                      -- Get JWT payload from dynamic metadata (set by jwt_authn filter)
                      local metadata = request_handle:streamInfo():dynamicMetadata()
                      local jwt_data = metadata:get("envoy.filters.http.jwt_authn")

                      if jwt_data ~= nil then
                        local payload = jwt_data["jwt_payload"]

                        if payload ~= nil then
                          -- Set authentication headers that backend expects
                          request_handle:headers():add("X-ROS-Authenticated", "true")
                          request_handle:headers():add("X-ROS-Auth-Method", "Envoy-Native-JWT")

                          -- Extract user ID (sub claim)
                          if payload["sub"] ~= nil then
                            request_handle:headers():add("X-ROS-User-ID", tostring(payload["sub"]))
                          end

                          -- Extract username (preferred_username claim)
                          if payload["preferred_username"] ~= nil then
                            request_handle:headers():add("X-ROS-User-Name", tostring(payload["preferred_username"]))
                          end

                          -- Extract client ID (azp or client_id claim)
                          if payload["azp"] ~= nil then
                            request_handle:headers():add("X-Client-ID", tostring(payload["azp"]))
                          elseif payload["client_id"] ~= nil then
                            request_handle:headers():add("X-Client-ID", tostring(payload["client_id"]))
                          end

                          -- Forward the bearer token (strip "Bearer " prefix)
                          local auth_header = request_handle:headers():get("authorization")
                          if auth_header ~= nil then
                            local token = string.gsub(auth_header, "^Bearer ", "")
                            request_handle:headers():add("X-Bearer-Token", token)
                          end

                          -- Log authentication for debugging
                          request_handle:logInfo("JWT authenticated: " .. tostring(payload["sub"]))
                        end
                      end
                    end

              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

      clusters:
      # ROS ingress backend (same pod, different port)
      - name: ros-ingress-backend
        connect_timeout: 5s
        type: STATIC
        load_assignment:
          cluster_name: ros-ingress-backend
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8081

      # Keycloak JWKS endpoint for JWT signature verification
      - name: keycloak_jwks
        connect_timeout: 5s
        type: STRICT_DNS
        load_assignment:
          cluster_name: keycloak_jwks
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Values.jwt_auth.keycloak.url | replace "https://" "" | replace "http://" "" }}
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: {{ .Values.jwt_auth.keycloak.url | replace "https://" "" | replace "http://" "" }}

    # Admin interface for monitoring and debugging
    admin:
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: {{ .Values.jwt_auth.envoy.adminPort }}
{{- end }}
