{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ros-ocp.fullname" . }}-rosocp-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    app.kubernetes.io/name: rosocp-api
spec:
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
      app.kubernetes.io/name: rosocp-api
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
      path: /metrics
      scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ros-ocp.fullname" . }}-rosocp-processor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: processor
    app.kubernetes.io/name: rosocp-processor
spec:
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: processor
      app.kubernetes.io/name: rosocp-processor
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
      path: /metrics
      scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ros-ocp.fullname" . }}-rosocp-recommendation-poller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: poller
    app.kubernetes.io/name: rosocp-recommendation-poller
spec:
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: poller
      app.kubernetes.io/name: rosocp-recommendation-poller
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
      path: /metrics
      scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ros-ocp.fullname" . }}-kruize
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ros-ocp.labels" . | nindent 4 }}
    app.kubernetes.io/component: optimization
    app.kubernetes.io/name: kruize
spec:
  selector:
    matchLabels:
      {{- include "ros-ocp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: optimization
      app.kubernetes.io/name: kruize
  endpoints:
    - port: http
      interval: {{ .Values.monitoring.scrapeInterval }}
      path: /q/metrics
      scheme: http
{{- end }}

