name: Lint and Validate Helm Chart

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'ros-ocp/**'
  workflow_dispatch:

jobs:
  helm-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm version

    - name: Lint Helm chart
      run: |
        echo "=== Linting Helm chart ==="
        cd ros-ocp
        helm lint .

    - name: Validate Helm templates
      run: |
        echo "=== Validating Helm templates ==="
        cd ros-ocp

        # Template validation without cluster connection
        echo "Running template validation..."
        helm template ros-ocp-test . --debug --dry-run
        echo "✓ Helm template validation completed successfully"
        
        # Additional template checks
        echo "Checking template output for common issues..."
        helm template ros-ocp-test . | grep -E "(apiVersion|kind|metadata)" | head -10
        echo "✓ Template structure validation completed"


