name: Lint and Validate Helm Chart

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'ros-ocp/**'
  workflow_dispatch:

jobs:
  helm-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm version

    - name: Lint Helm chart
      run: |
        echo "=== Linting Helm chart ==="
        cd ros-ocp
        helm lint .

    - name: Validate Helm templates
      run: |
        echo "=== Validating Helm templates ==="
        cd ros-ocp

        # Template with strict validation
        echo "Running strict template validation..."
        helm template ros-ocp-test . --validate
        echo "✓ Helm template validation completed successfully"


